version: "3"

services:
  webapp:
    build: .
    image: findincommon
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - mongodb
    networks:
      - webnet
  mongodb:
    image: mongo:4.0.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
# These two lines don't work on windows 7
#    volumes:
#      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    networks:
      - webnet

networks:
  webnet: