version: "3"

services:
  springboot:
    build: ./backend
    image: findincommon_backend
    environment:
      - NODE_ENV=development
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - webnet
  react:
    build: ./frontend
    image: findincommon_frontend
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - springboot
    networks:
      - webnet
  mongodb:
    image: mongo:4.0.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
# These two lines don't work on windows 7
#    volumes:
#      - ./data/db:/data/db
    ports:
      - "27017:27017"
    command: mongod --smallfiles
    networks:
      - webnet

networks:
  webnet:
