spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  data:
    mongodb:
      database: findincommon
      host: mongodb
      port: 27017
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 271078530261418
            clientSecret: 2db5899f1a89665501f1023bb3de3238
            redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
            scope: email
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect


---

spring:
  profiles: prod

